package fr.formation.inti.entities;
// Generated 6 avr. 2019 18:07:05 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "urbanproject")
public class Users implements java.io.Serializable {

	private int idusers;
	private String mail;
	private String pseudo;
	private String password;
	private Integer age;
	private String adress;
	private Set<Comment> comments = new HashSet<Comment>(0);

	public Users() {
	}

	public Users(int idusers, String mail, String password) {
		this.idusers = idusers;
		this.mail = mail;
		this.password = password;
	}

	public Users(int idusers, String mail, String pseudo, String password, Integer age, String adress,
			Set<Comment> comments) {
		this.idusers = idusers;
		this.mail = mail;
		this.pseudo = pseudo;
		this.password = password;
		this.age = age;
		this.adress = adress;
		this.comments = comments;
	}

	@Id

	@Column(name = "idusers", unique = true, nullable = false)
	public int getIdusers() {
		return this.idusers;
	}

	public void setIdusers(int idusers) {
		this.idusers = idusers;
	}

	@Column(name = "mail", nullable = false, length = 45)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "pseudo", length = 45)
	public String getPseudo() {
		return this.pseudo;
	}

	public void setPseudo(String pseudo) {
		this.pseudo = pseudo;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "adress")
	public String getAdress() {
		return this.adress;
	}

	public void setAdress(String adress) {
		this.adress = adress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

}
